### ISSUE TITLE
JSCK does not support minLength and maxLength tests of unicode surrogate pairs

### ISSUE THREAD

**Issue by automatthew** [pandastrike/jsck#42]
Test in question:

https://github.com/automatthew/JSON-Schema-Test-Suite/blob/develop/tests/draft3/minLength.json#L27-L30

Explanation of unicode surrogate pairs, needed to pass the test:
https://mathiasbynens.be/notes/javascript-encoding

Example of decoding
https://github.com/bestiejs/punycode.js/blob/221463da/punycode.js#L94-L128

**Comment by gilesbowkett** [comment]
every validator out there neglects to support this also. IIRC consensus was it's an impractical requirement.
