### ISSUE TITLE
Include mc-schema in bechmarks, It's faster

### ISSUE THREAD

**Issue by mctep** [pandastrike/jsck#76]
Hi! Can I take part in the competition https://github.com/pandastrike/jsck/issues/72? :-)

https://github.com/mctep/mc-schema

It passes all tests from https://github.com/json-schema/JSON-Schema-Test-Suite except of:
```js
var IGNORE = [
	'zeroTerminatedFloats.json',
	'refRemote.json',
	'one supplementary Unicode code point is not long enough',
	'two supplementary Unicode code points is long enough'
];
```

**Comment by mctep** [comment]
Forget it. I found some problems :-)

**Comment by mctep** [comment]
Ok. I can suggest that you use the same schema objects between tests in bencmarks. So modules cans to affect tests between modules like (z-schema). May be you should cloning schema object before setub lib?

**Comment by automatthew** [comment]
> May be you should cloning schema object before setup lib?

Yes, I think this would be a good prophylactic measure

**Comment by gilesbowkett** [comment]
In an ideal world, I wouldn't mind breaking out the benchmarks into their own repo. As it is, we can make tickets for these suggestions if need be.

**Comment by mctep** [comment]
Of course it is up to your up to deside.
I have noticed that you have comments like:
```
## Disabled because it refuses to accept one of our schema
```

As for the subject of the issue `is-my-json-valid` is faster than `mc-schema` according to your benchmarks. So I closed it.

**Comment by automatthew** [comment]
@mctep 

>  I have noticed that you have comments like...

I don't want to exclude any reasonable project, but I can't include validators that say a valid document is invalid.  Now that we have (json-schema-tests](https://www.npmjs.com/package/json-schema-tests), we can better assess problems with other validators and give the authors information on where they're failing.

**Comment by automatthew** [comment]
> As for the subject of the issue is-my-json-valid is faster than mc-schema according to your benchmarks. So I closed it.

Mere speed isn't the only consideration.  There are some features that I need in a validator that I would be willing to sacrifice performance to have.   I'd like to include your lib in the benchmarks whether or not it's the front-runner.

**Comment by mctep** [comment]
> Now that we have [json-schema-tests](https://www.npmjs.com/package/json-schema-tests)

It's a really great idea. I'will keep an eye on. Can I ask you some questions by email about this?

**Comment by automatthew** [comment]
> Can I ask you some questions by email about this?

Yes.  My email's in my GitHub profile.
