### ISSUE TITLE
update readme/docs

### ISSUE THREAD

**Issue by gilesbowkett** [pandastrike/jsck#80]
solves the real problem in #78.

work begun in branch `readme-update`, but needs to be completed. (fix for #78 merged to `master`.)

running `coffee tasks/build/docs.coffee` has a couple minor issues:

* degrades "advanced usage examples" link to draft 3
* undocumented pfm dependency
* adds commented-out code to `doc/tests.coffee`

**Comment by automatthew** [comment]
> degrades "advanced usage examples" link to draft 3

Fixed.  Edits to the README should be made to the [PFM source](https://github.com/pandastrike/jsck/blob/master/doc/README.pfm.md)
