### ISSUE TITLE
Feature request: line numbers on error

### ISSUE THREAD

**Issue by braco** [pandastrike/jsck#96]
Would be nice to use as a linter.

**Comment by automatthew** [comment]
Meaning errors caused by bugs in JSCK, or errors in the validated document, or ...?

**Comment by automatthew** [comment]
JSCK doesn't deal directly with strings containing JSON; it expects the schemas and documents to be JavaScript objects.  I typically use either CoffeeScript or YAML to represent my schemas and documents, providing them to JSCK only after parsing.

Line numbers for the inputs are thus impossible.  What is possible, and is actually better, is using JSON Pointers in validation error explanations to point directly to the section of schema and section of document that are concerned.
